from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewInfo(object):
    def setupUi(self, ViewInfo):
        ViewInfo.setObjectName("ViewInfo")
        ViewInfo.resize(581, 309)
        self.centralwidget = QtWidgets.QWidget(ViewInfo)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.authorsTab = QtWidgets.QWidget()
        self.authorsTab.setObjectName("authorsTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.authorsTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.authors = QtWidgets.QTableView(self.authorsTab)
        self.authors.setObjectName("authors")
        self.authors.setSelectionMode(QtWidgets.QTableView.SingleSelection)
        self.verticalLayout_2.addWidget(self.authors)
        self.addAuthor = QtWidgets.QPushButton(self.authorsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAuthor.sizePolicy().hasHeightForWidth())
        self.addAuthor.setSizePolicy(sizePolicy)
        self.addAuthor.setMinimumSize(QtCore.QSize(200, 0))
        self.addAuthor.setMaximumSize(QtCore.QSize(75, 23))
        self.addAuthor.setObjectName("addAuthor")
        self.verticalLayout_2.addWidget(self.addAuthor)
        self.tabWidget.addTab(self.authorsTab, "")
        self.booksTab = QtWidgets.QWidget()
        self.booksTab.setObjectName("booksTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.booksTab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.books = QtWidgets.QTableView(self.booksTab)
        self.books.setObjectName("books")
        self.books.setSelectionMode(QtWidgets.QTableView.SingleSelection)
        self.verticalLayout_4.addWidget(self.books)
        self.addBook = QtWidgets.QPushButton(self.booksTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addBook.sizePolicy().hasHeightForWidth())
        self.addBook.setSizePolicy(sizePolicy)
        self.addBook.setMinimumSize(QtCore.QSize(200, 0))
        self.addBook.setMaximumSize(QtCore.QSize(300, 16777215))
        self.addBook.setObjectName("addBook")
        self.verticalLayout_4.addWidget(self.addBook)
        self.tabWidget.addTab(self.booksTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        ViewInfo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ViewInfo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 21))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtWidgets.QMenu(self.menubar)
        self.fileMenu.setObjectName('fileMenu')
        self.authorsImport = QtWidgets.QAction(ViewInfo)
        self.authorsImport.setObjectName('authorsImport')
        self.authorsExport = QtWidgets.QAction(ViewInfo)
        self.authorsExport.setObjectName('authorsExport')
        self.fileMenu.addAction(self.authorsImport)
        self.fileMenu.addAction(self.authorsExport)
        self.menubar.addMenu(self.fileMenu)
        ViewInfo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ViewInfo)
        self.statusbar.setObjectName("statusbar")
        ViewInfo.setStatusBar(self.statusbar)

        self.retranslateUi(ViewInfo)
        self.tabWidget.setCurrentIndex(0)
        self.addAuthor.clicked.connect(ViewInfo.add_author)
        self.addBook.clicked.connect(ViewInfo.add_book)
        self.authorsImport.triggered.connect(ViewInfo.import_authors)
        self.authorsExport.triggered.connect(ViewInfo.export_authors)
        QtCore.QMetaObject.connectSlotsByName(ViewInfo)

    def retranslateUi(self, ViewInfo):
        _translate = QtCore.QCoreApplication.translate
        ViewInfo.setWindowTitle(_translate("ViewInfo", "Просмотр"))
        self.addAuthor.setText(_translate("ViewInfo", "Добавить автора"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.authorsTab), _translate("ViewInfo", "Авторы"))
        self.addBook.setText(_translate("ViewInfo", "Добавить книгу"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.booksTab), _translate("ViewInfo", "Книги"))
        self.fileMenu.setTitle(_translate("ViewInfo", "Файл"))
        self.authorsImport.setText(_translate("ViewInfo", "Импорт авторов..."))
        self.authorsExport.setText(_translate("ViewInfo", "Экспорт авторов..."))